name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies
  - r-base=3.5.3
  - p-base=3.7.7
  - r-dpylyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - pip:
     - plotyly
     - pandas
     - matplotlib
     - scikitlearn
     - numpy